version: "3.7"
services:
    talks-system:
        depends_on: 
            - db
        image: talks-system
        build: .
        ports:
            - 8080:80
        

    db:
        image: mysql:5.6
        environment:
            MYSQL_DATABASE: diccucou_talks
            MYSQL_USER: diccucou_talks
            MYSQL_PASSWORD: securepassword
            MYSQL_ROOT_PASSWORD: rootpassword
    
    adminer:
        depends_on: 
            - db
        image: adminer
        ports:
            - 8081:8080